config/routes.rb
# frozen_string_literal: true

# /workspaces/Inventory-Management-System/config/routes.rb
Rails.application.routes.draw do
  get "/products/index", to: "products#index"
  get "/forgot_password", to: "users#forgot_password"
  devise_for :users, controllers: { registrations: "custom_devise/registrations" }
  resources :users
  resources :storage_locations
  resources :roles
  resources :inventory_transactions
  resources :order_items
  get "orders/incoming", to: "orders#incoming", as: :incoming_orders
  get "orders/outgoing", to: "orders#outgoing", as: :outgoing_orders
  get "/orders/index", to: "orders#index"
  resources :orders do
    member do
      delete "remove_product/:product_id", to: "orders#remove_product", as: "remove_product"
    end
  end
  resources :orders
  resources :suppliers
  resources :categories
  resources :products
  resources :subcategories
  get "search", to: "search#index"
  get "/subcategories_by_category", to: "products#subcategories_by_category"

  root "products#index"
end

app/controllers/search_controller.rb
# frozen_string_literal: true

# /workspaces/Inventory-Management-System/app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @q = params[:q]
    @results = perform_search
    @products = @results[:products] || []
    @categories = @results[:categories] || []
    @subcategories = @results[:subcategories] || []
    @order_products = @results[:order_products] || []
    @orders = @results[:orders] || []
    @storage_locations = @results[:storage_locations] || []
    @suppliers = @results[:suppliers] || []
    @users = @results[:users] || []
  end

  private

  def perform_search
    # Use Ransack to search across multiple models

    results = {}

    # Search in 'categories' model
    results[:categories] = Category.ransack(name_or_description_cont: @q).result.to_a

    # Search in 'products' model
    results[:products] = Product.ransack(name_or_description_cont: @q).result.to_a

    # Search in 'orders' model
    results[:orders] = Order.ransack(status_or_description_cont: @q).result.to_a

    # Search in 'subcategories' model
    results[:subcategories] = Subcategory.ransack(name_or_description_cont: @q).result.to_a

    # Search in 'suppliers' model
    results[:suppliers] = Supplier.ransack(name_or_description_or_contact_info_cont: @q).result.to_a

    # Search in 'users' model
    results[:users] = User.ransack(email_or_first_name_or_last_name_or_role_cont: @q).result.to_a

    # Flatten the array of results and remove duplicates
    results.each { |key, value| results[key] = value.flatten.uniq }

    results
  end
end

app/helpers/search_helper.rb
# frozen_string_literal: true

# /workspaces/Inventory-Management-System/app/helpers/search_helper.rb
module SearchHelper
  def get_columns_for_model(model, products)
    case model.to_s
    when "User"
      ["id", "first_name", "Email", "Bio", "Role"]
    when "Supplier"
      ["id", "Address", "Contact_Info", "Description", "Name"]
    when "Subcategory"
      ["id", "Description", "Name"]
    when "StorageLocation"
      ["id", "Address", "Description", "Name"]
    when "Product"
      products.map do |product|
        [
          product.id.to_s,
          product.name.to_s,
          product.description.to_s,
          product.sku.to_s,
          number_with_precision(product.price, precision: 2).to_s,
          product.stock_quantity.to_s,
          product.category ? product.category.name.to_s : "",
          product.subcategory ? product.subcategory.name.to_s : "",
          product.supplier ? product.supplier.name.to_s : "",
        ]
      end
    when "Order"
      ["id", "Description", "Expected_Delivery", "Receiving_Address", "Sending_Address", "Products", "Status"]
    when "Category"
      ["id", "Name", "Subcategory", "Description"]
    else
      model_results.first.attributes.keys
    end
  end
end

app/views/search/_categories_search.html.erb
<!--/workspaces/Inventory-Management-System/app/views/search/_categories_search.html.erb-->
<script>
  $(document).ready(function() {
    var table = $('#categoryTable').DataTable({
      paging: true,
      ordering: true,
      selectable: true,
      fixedheader: true
    });
  });
</script>

    <div class="card shadow mb-4">
      <div class="card-header py-3 collapse-header" data-toggle="collapse" data-target="#categoryTableCollapse">
        <h6 class="m-0 font-weight-regular text-black">Categories</h6>
      </div>
      <div class="card-body collapse" id="categoryTableCollapse">
        <div class="table-responsive">
          <table class="table datatable-bordered" id="categoryTable" width="100%" cellspacing="0">
            <thead class="datatable-header">
              <tr>
                <th class="sortable" data-mdb-sort="id">ID</th>
                <th class="sortable" data-mdb-sort="name">Name</th>
                <th class="sortable" data-mdb-sort="email">Description</th>
              </tr>
            </thead>
            <tbody>
              <% @categories.each do |category| %>
                <tr>
                  <td><%= category.id %></td>
                  <td><%= link_to "#{category.name}", category_path(category) %></td>
                  <td><%= category.description %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

app/views/search/_orders_search.html.erb
<!--/workspaces/Inventory-Management-System/app/views/search/_orders_search.html.erb-->
<script>
  $(document).ready(function () {
      var ordersTable = $('#ordersTable').DataTable({
        processing: true,
        serverSide: true,
        paging: true,
        autowidth: true,
        ordering: true,
        searching: true,
        lengthChange: true,
        autoFill: true,
        lengthMenu: [5, 10, 25, 50, 100],
        ajax: {
          url: '<%= orders_index_path(format: :json) %>',
          type: 'GET',
          dataType: 'json',
          data: function (d) {
            // Add additional parameters if needed
            // Example: d.custom_param = 'value';
          }
        },

        columns: [
          { data: 'id' },
          { data: 'expected_delivery' },
          { data: 'status' },
          { data: 'sending_address' },
          { data: 'receiving_address' },
          { data: 'description' },
          { data: 'product_id' },
          { data: 'quantity_ordered' },
          { data: 'shipping_cost' },
          { data: 'order_total' }
          // Add more columns as needed
        ],
        columnDefs: [
          {
            targets: [3, 4], // Column indices (0-based) for sending_address and receiving_address
            render: function (data, type, row, meta) {
              // 'display' type will only affect the display and not sorting or filtering
              if (type === 'display') {
                return '<span style="font-size: 12px;">' + data + '</span>';
              }
              return data;
            },
          },
    {
            targets: [9, 8], // Column index (0-based) for the 'Total' column
            render: function (data, type, row, meta) {
              // 'display' type will only affect the display and not sorting or filtering
              if (type === 'display') {
                return '$' + data;
              }
              return data;
            },
          },
          // Add more columnDefs as needed
        ],
        language: {
          searchPlaceholder: "Search...", // Set a placeholder for the search input
        },
      });
  $('#ordersTable tbody').on('click', 'tr', function() {
        var data = ordersTable.row(this).data();
         console.log(data); // This will log the data object to the console.
         window.location.href = '/orders/' + data.id;
         });
       });
</script>

<div class="row">
  <div id="orders" class="col" >
    <div class="card shadow mb-4">
      <div class="card-header py-3 collapse-header" data-toggle="collapse" data-target="#ordersCardBody">
        <div class="d-flex justify-content-between align-items-center">
          <h6 class="m-0 font-weight-regular text-black">Orders</h6>
        </div>
      </div>
      <div class="card-body collapse" id="ordersCardBody">
        <div class="table-responsive">
          <table class="table datatable-bordered" id="ordersTable" width="100%" cellspacing="0">
            <thead class="datatable-header">
              <tr>
                <th class="sortable" data-mdb-sort="id">ID</th>
                <th class="sortable" data-mdb-sort="expected_delivery">Delivery EDA</th>
                <th class="sortable" data-mdb-sort="status">Status</th>
                <th class="sortable" data-mdb-sort="sending_address">Sending Address</th>
                <th class="sortable" data-mdb-sort="receiving_address">Receiving Address</th>
                <th class="sortable" data-mdb-sort="description">Tracking</th>
                <th class="sortable" data-mdb-sort="product_id">Product IDs</th>
                <th class="sortable" data-mdb-sort="quantity_ordered">Units</th>
                <th class="sortable" data-mdb-sort="shipping_cost">Shipping</th>
                <th class="sortable" data-mdb-sort="order_total">Total</th>
              </tr>
            </thead>
            <tbody>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/search/_products_search.html.erb
<!--/workspaces/Inventory-Management-System/app/views/search/_products_search.html.erb-->
<!--/workspaces/Inventory-Management-System/app/views/products/index.html.erb-->
<script>
  $(document).ready(function () {
    var productTable = $('#productTable').DataTable({
      processing: true,
      serverSide: true,
      paging: true,
      autowidth: true,
      ordering: true,
      searching: true,
      lengthChange: true,
      lengthMenu: [5, 10, 25, 50, 100],
        ajax: {
        url: '<%= products_index_path(format: :json) %>',
        type: 'GET',
        dataType: 'json',
        data: function (d) {
          // Add additional parameters if needed
          // Example: d.custom_param = 'value';
        }
      },
      columns: [
        { data: 'id' },
        { data: 'name' },
        { data: 'description' },
        { data: 'sku' },
        { data: 'price' },
        { data: 'stock_quantity' },
        { data: 'category' },
        { data: 'subcategory' },
        { data: 'supplier' },
      ],
      language: {
        searchPlaceholder: "Search...", // Set a placeholder for the search input
      },
    });
$('#productTable tbody').on('click', 'tr', function() {
       var data = productTable.row(this).data();
       console.log(data); // This will log the data object to the console.
       window.location.href = '/products/' + data.id;
       });
     });
</script>

<div class="row">
  <div id="products" class="col">
    <div class="card shadow mb-4">
      <div class="card-header py-3 -header" data-toggle="collapse" data-target="#productsCardBody">
        <div class="d-flex justify-content-between align-items-center">
          <h6 class="m-0 font-weight-regular text-black">Products</h6>
        </div>
      </div>
      <div class="card-body collapse" id="productsCardBody">
        <div class="table-responsive">
          <table class="table datatable-bordered" id="productTable" width="100%" cellspacing="0">
            <thead class="datatable-header">
              <tr>
                <th class="sortable" data-mdb-sort="id">ID</th>
                <th class="sortable" data-mdb-sort="name">Name</th>
                <th class="sortable" data-mdb-sort="description">Description</th>
                <th class="sortable" data-mdb-sort="sku">SKU</th>
                <th class="sortable" data-mdb-sort="price">Price</th>
                <th class="sortable" data-mdb-sort="quantity">Units</th>
                <th class="sortable" data-mdb-sort="category">Category</th>
                <th class="sortable" data-mdb-sort="subcategory">Subcategory</th>
                <th class="sortable" data-mdb-sort="supplier">Supplier</th>
              </tr>
            </thead>
            <tbody>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/search/_subcategories_search.html.erb
<!--/workspaces/Inventory-Management-System/app/views/search/_subcategories_search.html.erb-->
<script>
  $(document).ready(function() {
    var table = $('#subcategoryTable').DataTable({
      paging: true,
      ordering: true,
      selectable: true,
      fixedheader: true
    });
  });
</script>

<div class="card shadow mb-4">
  <div class="card-header py-3 collapse-header" data-toggle="collapse" data-target="#subcategoryTableCollapse">
    <h6 class="m-0 font-weight-regular text-black">Subcategories</h6>
  </div>
  <div class="card-body collapse" id="subcategoryTableCollapse">
    <div class="table-responsive">
      <table class="table datatable-bordered" id="subcategoryTable" width="100%" cellspacing="0">
        <thead class="datatable-header">
          <tr>
            <th class="sortable" data-mdb-sort="id">ID</th>
            <th class="sortable" data-mdb-sort="name">Name</th>
            <th class="sortable" data-mdb-sort="email">Category</th>
          </tr>
        </thead>
        <tbody>
          <% @subcategories.each do |subcategory| %>
            <tr>
              <td><%= subcategory.id %></td>
              <td><%= link_to "#{subcategory.name}", subcategory_path(subcategory) %></td>
              <td><%= link_to subcategory.category.name, subcategory.category %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/search/_suppliers_search.html.erb
<!--/workspaces/Inventory-Management-System/app/views/search/_suppliers_search.html.erb-->
<script>
  $(document).ready(function() {
    var table = $('#supplierTable').DataTable({
      paging: true,
      ordering: true,
      selectable: true,
      fixedheader: true
    });
  });
</script>

<div class="card shadow mb-4">
  <div class="card-header py-3 collapse-header" data-toggle="collapse" data-target="#supplierTableCollapse">
    <h6 class="m-0 font-weight-regular text-black">Suppliers</h6>
  </div>
  <div class="card-body collapse" id="supplierTableCollapse">
    <div class="table-responsive">
      <table class="table datatable-bordered" id="supplierTable" width="100%" cellspacing="0">
        <thead class="datatable-header">
          <tr>
            <th class="sortable" data-mdb-sort="id">ID</th>
            <th class="sortable" data-mdb-sort="name">Name</th>
            <th class="sortable" data-mdb-sort="contact">Contact</th>
            <th class="sortable" data-mdb-sort="description">Description</th>
            <th class="sortable" data-mdb-sort="address">Address</th>
          </tr>
        </thead>
        <tbody>
          <% @suppliers.each do |supplier| %>
            <tr>
              <td><%= supplier.id %></td>
              <td><%= link_to supplier.name, supplier %></td>
              <td><%= mail_to supplier.contact_info %></td>
              <td><%= supplier.description %></td>
              <td><%= link_to supplier.address, "https://www.google.com/maps?q=#{URI.encode_www_form_component(supplier.address)}", target: "_blank" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/search/_table_body.html.erb
<!--/workspaces/Inventory-Management-System/app/views/search/_table_body.html.erb-->
<!--<tbody>-->
  <%# model_results.each do |result| %>
<!--    <tr data-href="<%#= generate_path(result) %>">-->
      <%# columns.each do |attribute| %>
        <%# if attribute == 'id' %>
<!--          <td><%#= result.send(attribute.downcase) %></td>-->
        <%# else %>
<!--          <td><%#= link_to result.send(attribute.downcase), result %></td>-->
        <%# end %>
      <%# end %>
<!--    </tr>-->
  <%# end %>
<!--</tbody>-->

app/views/search/_table_header.html.erb
<!--/workspaces/Inventory-Management-System/app/views/search/_table_header.html.erb-->
<!--<thead class="datatable-header">
  <tr>
    <%# columns.each do |attribute| %>-->
<!--      <th class="sortable" data-mdb-sort="<%#= attribute %>">-->
        <%#= attribute.titleize %>
<!--      </th>-->
    <%# end %>
<!--  </tr>
</thead>
-->

app/views/search/_users_search.html.erb
<!--/workspaces/Inventory-Management-System/app/views/search/_users_search.html.erb-->
<script>
  $(document).ready(function() {
    var table = $('#userTable').DataTable({
      paging: true,
      ordering: true,
      selectable: true,
      fixedheader: true
    });
  });
</script>

<div class="card shadow mb-4">
  <div class="card-header py-3 collapse-header" data-toggle="collapse" data-target="#userTableCollapse">
    <h6 class="m-0 font-weight-regular text-black">Users</h6>
  </div>
  <div class="card-body collapse" id="userTableCollapse">
    <div class="table-responsive">
      <table class="table datatable-bordered" id="userTable" width="100%" cellspacing="0">
        <thead class="datatable-header">
          <tr>
            <th class="sortable" data-mdb-sort="id">ID</th>
            <th class="sortable" data-mdb-sort="name">Name</th>
            <th class="sortable" data-mdb-sort="email">Email</th>
            <th class="sortable" data-mdb-sort="role">Role</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= link_to "#{user.first_name} #{user.last_name}", user_path(user) %></td>
              <td><%= mail_to user.email %></td>
              <td><%= user.role.capitalize %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/search/index.html.erb
<!--/workspaces/Inventory-Management-System/app/views/search/index.html.erb-->
<% puts  @results.inspect  %>
<% if @users.empty? && @categories.empty? && @subcategories.empty? && @orders.empty? && @products.empty? && @suppliers.empty?
 %>
  <div class="alert alert-info" role="alert" style="margin-top: 100px; font-family: Philosopher; font-size: 50px; text-align:center" >
    No results found...
  </div>

<% else %>
  <% if @users.any? %>
    <%= render partial: 'users_search' %>
  <% end %>
  <% if @categories.any? %>
    <%= render partial: 'categories_search' %>
  <% end %>
  <% if @subcategories.any? %>
    <%= render partial: 'subcategories_search' %>
  <% end %>
  <% if @orders.any? %>
    <%= render partial: 'orders_search' %>
  <% end %>
  <% if @products.any? %>
    <%= render partial: 'products_search' %>
  <% end %>
  <% if @suppliers.any? %>
    <%= render partial: 'suppliers_search' %>
  <% end  %>
<% end %>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    var dataTable = document.querySelectorAll(".datatable-bordered tbody");

    dataTable.forEach(function (table) {
      table.addEventListener("click", function (event) {
        var targetRow = event.target.closest("tr[data-href]");

        if (targetRow) {
          window.location.href = targetRow.dataset.href;
        }
      });
    });
  });
</script>