config/routes.rb
# frozen_string_literal: true

# /workspaces/Inventory-Management-System/config/routes.rb
Rails.application.routes.draw do
  get "/products/index", to: "products#index"
  get "/forgot_password", to: "users#forgot_password"
  devise_for :users, controllers: { registrations: "custom_devise/registrations" }
  resources :users
  resources :storage_locations
  resources :roles
  resources :inventory_transactions
  resources :order_items
  get "orders/incoming", to: "orders#incoming", as: :incoming_orders
  get "orders/outgoing", to: "orders#outgoing", as: :outgoing_orders
  get "/orders/index", to: "orders#index"
  resources :orders do
    member do
      delete "remove_product/:product_id", to: "orders#remove_product", as: "remove_product"
    end
  end
  resources :orders
  resources :suppliers
  resources :categories
  resources :products
  resources :subcategories
  get "search", to: "search#index"
  get "/subcategories_by_category", to: "products#subcategories_by_category"

  root "products#index"
end

app/models/subcategory.rb
# frozen_string_literal: true

# /workspaces/Inventory-Management-System/app/models/subcategory.rb
# == Schema Information
#
# Table name: subcategories
#
#  id          :integer          not null, primary key
#  description :text
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer          not null
#  company_id  :integer
#
# Indexes
#
#  index_subcategories_on_category_id  (category_id)
#  index_subcategories_on_company_id   (company_id)
#
# Foreign Keys
#
#  category_id  (category_id => categories.id)
#  company_id   (company_id => companies.id)
#
class Subcategory < ApplicationRecord
  belongs_to :category
  has_many :products
  belongs_to :company
  include Ransackable
end

app/controllers/subcategories_controller.rb
# frozen_string_literal: true

# /workspaces/Inventory-Management-System/app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :set_subcategory, only: [:show, :edit, :update, :destroy]

  # GET /subcategories or /subcategories.json
  def index
    @subcategories = Subcategory.includes(:category, products: [:supplier]).all
    authorize(@subcategory)
  end

  # GET /subcategories/1 or /subcategories/1.json
  def show
    @subcategory = Subcategory.find(params[:id])
    authorize(@subcategory)
    # @products = @category.products.includes(:subcategory)
  end

  # GET /subcategories/new
  def new
    @subcategory = Subcategory.new
    authorize(@subcategory)
  end

  # GET /subcategories/1/edit
  def edit
    @subcategory = Subcategory.find(params[:id])
    authorize(@subcategory)
  end

  # POST /subcategories or /subcategories.json
  def create
    @subcategory = Subcategory.new(subcategory_params)
    authorize(@subcategory)
    respond_to do |format|
      if @subcategory.save
        format.html { redirect_to(subcategory_url(@subcategory), notice: "Subcategory was successfully created.") }
        format.json { render(:show, status: :created, location: @subcategory) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @subcategory.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /subcategories/1 or /subcategories/1.json
  def update
    @subcategory = Subcategory.find(params[:id])
    authorize(@subcategory)
    respond_to do |format|
      if @subcategory.update(subcategory_params)
        format.html { redirect_to(subcategory_url(@subcategory), notice: "Subcategory was successfully updated.") }
        format.json { render(:show, status: :ok, location: @subcategory) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @subcategory.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /subcategories/1 or /subcategories/1.json
  def destroy
    authorize(@subcategory)
    @subcategory.update(category_id: nil)
    @subcategory.update(category: nil)
    # Disassociate products from the subcategory
    @subcategory.products.each do |product|
      product.update(subcategory: nil)
    end

    @subcategory.destroy

    respond_to do |format|
      format.html { redirect_to(subcategories_url, notice: "Subcategory was successfully destroyed.") }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_subcategory
    @subcategory = Subcategory.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def subcategory_params
    params.require(:subcategory).permit(:name, :description, :category_id)
  end
end

app/views/subcategories/_form.html.erb
<!--/workspaces/Inventory-Management-System/app/views/subcategories/_form.html.erb-->
<%= form_with(model: subcategory) do |form| %>
  <% if subcategory.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subcategory.errors.count, "error") %> prohibited this subcategory from being saved:</h2>

      <ul>
        <% subcategory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: "Select a category" }, class: "category-select" %>
  </div>

  <%= form.hidden_field :company_id, value: current_user.company_id %>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/subcategories/_subcategory.html.erb
<!--/workspaces/Inventory-Management-System/app/views/subcategories/_subcategory.html.erb-->
<p>
  <div class="header">
    <h1 style="white-space: nowrap;"><%= link_to @subcategory.category.name, @subcategory.category %> > </h1>
    <h3 style="white-space: nowrap; padding-left: 10px; margin-bottom: 1.5px;"> <%= @subcategory.name %></h2>
    <div class="container text-right">
      <h1><%= link_to "New Product", new_product_path %></h1>
    </div>
  </div>
  <script>
    $(document).ready(function() {
      var table = $('#dataTable').DataTable({
        paging: true,
        ordering: true,
        selectable: true,
        fixedheader: true
      });
    });
  </script>
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-regular text-black">Full Inventory</h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table datatable-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead class="datatable-header">
            <tr>
              <th class="sortable" data-mdb-sort="name">ID</th>
              <th class="sortable" data-mdb-sort="name">Name</th>
              <th class="sortable" data-mdb-sort="description">Description</th>
              <th class="sortable" data-mdb-sort="sku">SKU</th>
              <th class="sortable" data-mdb-sort="price">Price</th>
              <th class="sortable" data-mdb-sort="quantity">Units</th>
              <th class="sortable" data-mdb-sort="category">Category</th>
              <th class="sortable" data-mdb-sort="subcategory">Subcategory</th>
              <th class="sortable" data-mdb-sort="supplier">Supplier</th>
            </tr>
          </thead>
        <tbody>
          <% subcategory.products.each do |product| %>
            <tr>
              <td><%= product.id %></td>
              <td><%= link_to product.name, product %></td>
              <td><%= product.description %></td>
              <td><%= product.sku %></td>
              <td>$<%= number_with_precision(product.price, precision: 2) %></td>
              <td><%= product.stock_quantity %></td>
              <td><%= link_to product.category.name, product.category %></td>
              <td><%= link_to product.subcategory.name, product.subcategory %></td>
              <td><%= link_to product.supplier.name, product.supplier %></td>
            </tr>
          <% end %>
        </tbody>
        </table>
      </div>
    </div>
  </div>
  <div>
    <% if current_user.role == "admin" || current_user.role == "manager" %>
      <%= button_to "Edit #{@subcategory.name}", edit_subcategory_path(@subcategory), method: :get %>
      <p></p>
      <%= button_to "All Categories", categories_path, method: :get %>
      <p></p>
      <%= button_to "Delete #{@subcategory.name}", @subcategory, method: :delete %>
    <% elsif current_user.role == "staff" %>
      <%= button_to "All Categories", categories_path, method: :get %>
    <% end %>
  </div>
</div>

app/views/subcategories/edit.html.erb
<!--/workspaces/Inventory-Management-System/app/views/subcategories/edit.html.erb-->
<h1>Editing subcategory</h1>

<%= render "form", subcategory: @subcategory %>

<br>

<div>
  <%= link_to "Show this subcategory", @subcategory %> |
  <%= link_to "Back to Category Index", categories_path %>
</div>

app/views/subcategories/index.html.erb
<!--/workspaces/Inventory-Management-System/app/views/subcategories/index.html.erb-->

<h1>Subcategories</h1>

<div id="subcategories">
  <% @subcategories.each do |subcategory| %>
    <%= render subcategory %>
    <p>
      <%= link_to "Show this subcategory", subcategory %>
    </p>
  <% end %>
</div>

<%= link_to "New subcategory", new_subcategory_path %>

app/views/subcategories/new.html.erb
<!--/workspaces/Inventory-Management-System/app/views/subcategories/new.html.erb-->
<h1>New subcategory</h1>

<%= render "form", subcategory: @subcategory %>

<br>

<div>
  <%= link_to "Back to subcategories", subcategories_path %>
</div>

app/views/subcategories/show.html.erb
<!--/workspaces/Inventory-Management-System/app/views/subcategories/show.html.erb-->

<%= render @subcategory %>