config/routes.rb
# frozen_string_literal: true

# /workspaces/Inventory-Management-System/config/routes.rb
Rails.application.routes.draw do
  get "/products/index", to: "products#index"
  get "/forgot_password", to: "users#forgot_password"
  devise_for :users, controllers: { registrations: "custom_devise/registrations" }
  resources :users
  resources :storage_locations
  resources :roles
  resources :inventory_transactions
  resources :order_items
  get "orders/incoming", to: "orders#incoming", as: :incoming_orders
  get "orders/outgoing", to: "orders#outgoing", as: :outgoing_orders
  get "/orders/index", to: "orders#index"
  resources :orders do
    member do
      delete "remove_product/:product_id", to: "orders#remove_product", as: "remove_product"
    end
  end
  resources :orders
  resources :suppliers
  resources :categories
  resources :products
  resources :subcategories
  get "search", to: "search#index"
  get "/subcategories_by_category", to: "products#subcategories_by_category"

  root "products#index"
end

app/models/category.rb
# frozen_string_literal: true

# /workspaces/Inventory-Management-System/app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :integer          not null, primary key
#  description :string
#  name        :string
#  subcategory :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  company_id  :integer
#
# Indexes
#
#  index_categories_on_company_id  (company_id)
#
# Foreign Keys
#
#  company_id  (company_id => companies.id)
#
class Category < ApplicationRecord
  has_many :products
  has_many :subcategories
  belongs_to :company
  include Ransackable
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# /workspaces/Inventory-Management-System/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.all.includes(:subcategories)
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.find(params[:id])
    @products = @category.products.includes(:category, :subcategory, :supplier)
    authorize(@category)
  end

  # GET /categories/new
  def new
    @category = Category.new
    authorize(@category)
  end

  # GET /categories/1/edit
  def edit
    authorize(@category)
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    authorize(@category)

    respond_to do |format|
      if @category.save
        format.html { redirect_to(category_url(@category), notice: "Category was successfully created.") }
        format.json { render(:show, status: :created, location: @category) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @category.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    authorize(@category)
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to(category_url(@category), notice: "Category was successfully updated.") }
        format.json { render(:show, status: :ok, location: @category) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @category.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    authorize(@category)
    @category.products.each do |product|
      product.update(category: nil)
    end
    @category.destroy
    respond_to do |format|
      format.html { redirect_to(categories_url, notice: "Category was successfully destroyed.") }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:id, :name, :description, :subcategory, :company_id)
  end

  def authorize_category
    authorize(Category)
  end
end

app/views/categories/_category.html.erb
<!--/workspaces/Inventory-Management-System/app/views/categories/_category.html.erb-->
<div class="header">
  <h1><%= @category.name %></h1>
  <div class="container text-right">
    <h1><%= link_to "New Product", new_product_path %></h1>
  </div>
</div>
<script>
  $(document).ready(function() {
    var table = $('#dataTable').DataTable({
      paging: true,
      ordering: true,
      selectable: true,
      fixedheader: true
    });
  });
</script>
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-regular text-black">Full Inventory</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table datatable-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead class="datatable-header">
          <tr>
            <th class="sortable" data-mdb-sort="name">ID</th>
            <th class="sortable" data-mdb-sort="name">Name</th>
            <th class="sortable" data-mdb-sort="description">Description</th>
            <th class="sortable" data-mdb-sort="sku">SKU</th>
            <th class="sortable" data-mdb-sort="price">Price</th>
            <th class="sortable" data-mdb-sort="quantity">Units</th>
            <th class="sortable" data-mdb-sort="category">Category</th>
            <th class="sortable" data-mdb-sort="subcategory">Subcategory</th>
            <th class="sortable" data-mdb-sort="supplier">Supplier</th>
          </tr>
        </thead>
        <tbody>
          <% category.products.each do |product| %>
            <tr>
              <td><%= product.id %></td>
              <td><%= link_to product.name, product %></td>
              <td><%= product.description %></td>
              <td><%= product.sku %></td>
              <td>$<%= number_with_precision(product.price, precision: 2) %></td>
              <td><%= product.stock_quantity %></td>
              <td><%= link_to product.category.name, product.category %></td>
              <td><%= link_to product.subcategory.name, product.subcategory %></td>
              <td><%= link_to product.supplier.name, product.supplier %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div>
  <% if policy(@category).edit? %>
    <%= button_to "Edit #{@category.name}", edit_category_path(@category), method: :get %>
    <p></p>
    <%= button_to "All Categories", categories_path, method: :get %>
    <p></p>
    <%= button_to "Delete #{@category.name}", @category, method: :delete %>
  <% elsif current_user.role == "staff" %>
    <%= button_to "All Categories", categories_path, method: :get %>
  <% end %>
</div>
</div>

app/views/categories/_form.html.erb
<!--/workspaces/Inventory-Management-System/app/views/categories/_form.html.erb-->
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <%= form.hidden_field :company_id, value: current_user.company_id %>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<!--/workspaces/Inventory-Management-System/app/views/categories/edit.html.erb-->
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<!--/workspaces/Inventory-Management-System/app/views/categories/index.html.erb-->
<style>
  .subcategories {
    display: none;
  }
  .subcategory-item {
    margin-left: 30px; /* Adjust the indentation as needed */
  }
  /* Add cursor property for the category links */
  .category-link:hover {
    cursor: pointer;
  }

  .header {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .header h1 {
    flex: 1;
  }

  .header .col {
    text-align: center;
  }

  .header .col.right {
    text-align: right;
  }
</style>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function() {
    $(".category-link").click(function() {
      var subcategoryList = $(this).next(".subcategories");
      subcategoryList.slideToggle();
    });
  });
</script>

<div class="header">
  <h1>Categories</h1>
  <% if current_user.role == "admin" || current_user.role == "manager" %>
    <div class="col">
      <div id="create_category">
        <h1><%= link_to "New Category", new_category_path %></h1>
      </div>
    </div>
    <div class="col right">
      <div id="create_subcategory">
        <h1><%= link_to "New Subcategory", new_subcategory_path %></h1>
      </div>
    </div>
  <% end %>
</div>
<hr>

<div id="categories">
  <% @categories.each do |category| %>
    <div class="category">
      <h5 class="category-link">
        <%= link_to category.name, category %><i class="fas fa-chevron-down" style="float: right;"></i>
      </h5>
      <div class="subcategories">
        <% category.subcategories.each do |subcategory| %>
          <h6 class="subcategory-item"><%= link_to subcategory.name, subcategory %></h6>
        <% end %>
      </div>
    </div>
    <hr>
  <% end %>
</div>

app/views/categories/new.html.erb
<!--/workspaces/Inventory-Management-System/app/views/categories/new.html.erb-->
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<!--/workspaces/Inventory-Management-System/app/views/categories/show.html.erb-->



<%= render @category %>