config/routes.rb
# frozen_string_literal: true

# /workspaces/Inventory-Management-System/config/routes.rb
Rails.application.routes.draw do
  get "/products/index", to: "products#index"
  get "/forgot_password", to: "users#forgot_password"
  devise_for :users, controllers: { registrations: "custom_devise/registrations" }
  resources :users
  resources :storage_locations
  resources :roles
  resources :inventory_transactions
  resources :order_items
  get "orders/incoming", to: "orders#incoming", as: :incoming_orders
  get "orders/outgoing", to: "orders#outgoing", as: :outgoing_orders
  get "/orders/index", to: "orders#index"
  resources :orders do
    member do
      delete "remove_product/:product_id", to: "orders#remove_product", as: "remove_product"
    end
  end
  resources :orders
  resources :suppliers
  resources :categories
  resources :products
  resources :subcategories
  get "search", to: "search#index"
  get "/subcategories_by_category", to: "products#subcategories_by_category"

  root "products#index"
end

app/models/product.rb
# frozen_string_literal: true

# /workspaces/Inventory-Management-System/app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id             :integer          not null, primary key
#  description    :string
#  name           :string
#  price          :decimal(, )
#  sku            :integer
#  stock_quantity :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  branch_id      :integer
#  category_id    :integer          not null
#  company_id     :integer
#  subcategory_id :integer          not null
#  supplier_id    :integer
#
# Indexes
#
#  index_products_on_branch_id                        (branch_id)
#  index_products_on_category_id                      (category_id)
#  index_products_on_company_and_branch_and_category  (company_id,branch_id,category_id)
#  index_products_on_company_id                       (company_id)
#  index_products_on_subcategory_id                   (subcategory_id)
#  index_products_on_supplier_id                      (supplier_id)
#
# Foreign Keys
#
#  branch_id       (branch_id => branches.id)
#  category_id     (category_id => categories.id)
#  company_id      (company_id => companies.id)
#  subcategory_id  (subcategory_id => subcategories.id)
#  supplier_id     (supplier_id => suppliers.id)
#
class Product < ApplicationRecord
  belongs_to :company
  has_many :branches
  belongs_to :category
  belongs_to :subcategory
  belongs_to :supplier
  has_many :order_products, dependent: :destroy
  has_many :orders, through: :order_products, dependent: :destroy
  include Ransackable

  def calculate_dynamic_stock_quantity
    starting_stock = product.stock_quantity
    starting_stock + order_products.sum do |order_product|
      case order_product.transaction_type
      when "purchase_from_supplier", "refund_to_customer"
        order_product.quantity_ordered
      when "sale_to_customer", "return_to_supplier", "stock_loss"
        -order_product.quantity_ordered
      else
        0
      end
    end
  end

  def supplier_name
    supplier&.name
  end

  def category_name
    category&.name
  end

  def subcategory_name
    subcategory&.name
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

# /workspaces/Inventory-Management-System/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  respond_to :html, :datatables

  # GET /products or /products.json
  def index
    @products = Product.all
    authorize(@products)
    respond_to do |format|
      format.html
      format.json { render(json: ProductDatatable.new(view_context).as_json) }
    end
  end

  # GET /products/1 or /products/1.json
  def show
    @product = Product.includes(:category, :subcategory, :supplier).find(params[:id])
    authorize(@product)
  end

  # GET /products/new
  def new
    @product = Product.new
    authorize(@product)
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    authorize(@product)
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    authorize(@product)

    respond_to do |format|
      if @product.save
        format.html { redirect_to(product_url(@product), notice: "Product was successfully created.") }
        format.json { render(:show, status: :created, location: @product) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @product.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    @product = Product.find(params[:id])
    authorize(@product)
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to(product_url(@product), notice: "Product was successfully updated.") }
        format.json { render(:show, status: :ok, location: @product) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @product.errors, status: :unprocessable_entity) }
      end
    end
  rescue ActiveRecord::RecordNotFound
    # Handle the case where the product with the given ID is not found
    flash[:alert] = "Product not found"
    redirect_to(products_url)
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    authorize(@product)
    respond_to do |format|
      format.html { redirect_to(products_url, notice: "Product was successfully destroyed.") }
      format.json { head(:no_content) }
    end
  end

  def subcategories_by_category
    @product = Product.new
    authorize(@product)
    category_id = params[:category_id]
    subcategories = Subcategory.where(category_id: category_id)

    render(json: { subcategories: subcategories })
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :sku,
      :price,
      :stock_quantity,
      :category_id,
      :subcategory_id,
      :supplier_id,
      :company_id,
      :branch_id,
    )
  end
end

app/views/products/_form.html.erb
<!--/workspaces/Inventory-Management-System/app/views/products/_form.html.erb-->
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <script>
    $(document).ready(function() {
      $('form').submit(function(e) {
        if ($.trim($('#product_name').val()) === '' ||
            !/^\d{6}$/.test($('#product_sku').val()) ||
            !/^\d+(?:\.\d{1,2})?$/.test($('#product_price').val()) ||
            !/^\d{1,5}$/.test($('#product_stock_quantity').val()) ||
            $('#product_category_id').val() === '') {
          e.preventDefault(); // Prevent form submission
          alert('Please fill in all fields correctly.');
        }
      });
    });
  </script>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :sku, style: "display: block" %>
    <%= form.number_field :sku, pattern: "\\d{6}", title: "Please enter a 6-digit number." %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price, step: "0.01", pattern: "^\\d+(\\.\\d{1,2})?$", title: "Please enter a valid price with up to 2 decimal places." %>
  </div>

  <div>
    <%= form.label :stock_quantity, style: "display: block" %>
    <%= form.number_field :stock_quantity, max: 9999, title: "Please enter a value below 5 digits." %>
  </div>

  <%= form.hidden_field :company_id, value: current_user.company_id %>
  <%= form.hidden_field :branch_id, value: current_user.branch_id %>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: "Select a category" }, class: "category-select" %>
  </div>

  <div>
    <%= form.label :subcategory_id, style: "display: block" %>
    <%= form.collection_select :subcategory_id, [], :id, :name, { prompt: "Select a subcategory" }, class: "subcategory-select" %>
  </div>

  <div>
    <%= form.label :supplier_id, style: "display: block" %>
    <%= form.collection_select :supplier_id, Supplier.all, :id, :name, prompt: "Select a supplier" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
<script>
  $(document).ready(function() {
    // Function to update subcategory dropdown based on selected category
    function updateSubcategories() {
      var selectedCategoryId = $('.category-select').val();

      // Enable subcategory dropdown and set minimum width
      var subcategorySelect = $('.subcategory-select');
      subcategorySelect.prop('disabled', false);
      subcategorySelect.css('min-width', '150px');

      // Fetch subcategories for the selected category using AJAX
      $.ajax({
        url: '/subcategories_by_category',
        method: 'GET',
        data: { category_id: selectedCategoryId },
        success: function(data) {
          // Update subcategory dropdown options
          var subcategories = data.subcategories;
          subcategorySelect.empty();

          $.each(subcategories, function(index, subcategory) {
            subcategorySelect.append('<option value="' + subcategory.id + '">' + subcategory.name + '</option>');
          });
        }
      });
    }

    // Event listener for changes in the category dropdown
    $('.category-select').change(function() {
      updateSubcategories();
    });
  });
</script>

app/views/products/_product.html.erb
<!--/workspaces/Inventory-Management-System/app/views/products/_product.html.erb-->
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Sku:</strong>
    <%= product.sku %>
  </p>

  <p>
    <strong>Price:</strong>
    $<%= number_with_precision(product.price, precision: 2) %>
  </p>

  <p>
    <strong>Stock quantity:</strong>
    <%= product.stock_quantity %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= product.category.name %>
  </p>

  <p>
    <strong>Subcategory:</strong>
    <%= product.subcategory.name %>
  </p>

  <p>
    <strong>Supplier:</strong>
    <%= product.supplier.name %>
  </p>

</div>

app/views/products/edit.html.erb
<!--/workspaces/Inventory-Management-System/app/views/products/edit.html.erb-->
<h1>Editing <%= @product.name %></h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<!--/workspaces/Inventory-Management-System/app/views/products/index.html.erb-->
<head>
  <%#= stylesheet_link_tag 'dataTables_custom', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<div class="header">
  <h1>Products</h1>
  <% if current_user.role == "admin" || current_user.role == "manager" %>
    <div class="container text-right">
      <div class="row">
        <div id="create_product" class="col">
          <h1><%= link_to "New Product", new_product_path %></h1>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script>
  $(document).ready(function () {
    var productTable = $('#productTable').DataTable({
      processing: true,
      serverSide: true,
      paging: true,
      autowidth: true,
      ordering: true,
      searching: true,
      lengthChange: true,
      lengthMenu: [5, 10, 25, 50, 100],
        ajax: {
        url: '<%= products_index_path(format: :json) %>',
        type: 'GET',
        dataType: 'json',
        data: function (d) {
          // Add additional parameters if needed
          // Example: d.custom_param = 'value';
        }
      },
      columns: [
        { data: 'id' },
        { data: 'name' },
        { data: 'description' },
        { data: 'sku' },
        { data: 'price' },
        { data: 'stock_quantity' },
        { data: 'category' },
        { data: 'subcategory' },
        { data: 'supplier' },
      ],
      language: {
        searchPlaceholder: "Search...", // Set a placeholder for the search input
      },
    });
$('#productTable tbody').on('click', 'tr', function() {
       var data = productTable.row(this).data();
       console.log(data); // This will log the data object to the console.
       window.location.href = '/products/' + data.id;
       });
     });
</script>

<div class="row">
  <div id="products" class="col">
    <div class="card shadow mb-4">
      <div class="card-header py-3 -header" data-toggle="" data-target="#productsCardBody">
        <div class="d-flex justify-content-between align-items-center">
          <h6 class="m-0 font-weight-regular text-black">Products</h6>
        </div>
      </div>
      <div class="card-body " id="productsCardBody">
        <div class="table-responsive">
          <table class="table datatable-bordered" id="productTable" width="100%" cellspacing="0">
            <thead class="datatable-header">
              <tr>
                <th class="sortable" data-mdb-sort="id">ID</th>
                <th class="sortable" data-mdb-sort="name">Name</th>
                <th class="sortable" data-mdb-sort="description">Description</th>
                <th class="sortable" data-mdb-sort="sku">SKU</th>
                <th class="sortable" data-mdb-sort="price">Price</th>
                <th class="sortable" data-mdb-sort="quantity">Units</th>
                <th class="sortable" data-mdb-sort="category">Category</th>
                <th class="sortable" data-mdb-sort="subcategory">Subcategory</th>
                <th class="sortable" data-mdb-sort="supplier">Supplier</th>
              </tr>
            </thead>
            <tbody>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/products/new.html.erb
<!--/workspaces/Inventory-Management-System/app/views/products/new.html.erb-->
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<!--/workspaces/Inventory-Management-System/app/views/products/show.html.erb-->


<%= render @product %>

<div>
  <% if current_user.role == "admin" %>
    <%= button_to "Edit #{@product.name}", edit_product_path, method: :get %> 
    <p></p>
    <%= button_to "All Products", products_path, method: :get %>
    <p></p>
    <%= button_to "Delete Product", product_path, method: :delete %>
  <% elsif current_user.role == "manager" %>
    <%= button_to "Edit #{@product}", edit_product_path, method: :get %> 
    <p></p>
    <%= button_to "All Products", products_path, method: :get %>
    <p></p>
    <%= button_to "Delete Product", product_path, method: :delete %>
  <% elsif current_user.role == "staff" %>
    <%= button_to "All Products", products_path, method: :get %>  <% end %>
</div>